<?php

namespace backend\controllers;

use Yii;
use backend\models\AdminMoneylog;
use backend\models\AdminMember;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use common\helps\ExportExcelController;
use backend\models\AdminUserRole;
use backend\models\AdminUser;
/**
 * AdminMoneylogController implements the CRUD actions for AdminMoneylog model.
 */
class AdminMoneylogController extends Controller
{
    /**
     * @inheritdoc
     */
    public $layout = "lte_main";
    public $admin_id;
    public $role_id;
    public $admin_user;

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->admin_id = yii::$app->session['__id'];
        //根据管理员id判断管理员的角色，超级管理员role_id为1
        $this->role_id = AdminUserRole::findOne(['user_id'=>yii::$app->session['__id']])->role_id;
        $this->admin_user = AdminUser::findOne(['id'=>yii::$app->session['__id']]);

    }
    /**
     * Lists all AdminMoneylog models.
     * @return mixed
     */
    public function actionIndex()
    {
        $typer[1] = '线上充值';
        $typer[2] = '线下充值';
        $typer[3] = '提现记录';
        $typer[4] = '提盈记录';
        $typer[5] = '追加记录';
        $query = AdminMoneylog::find()->joinWith('member');
        $querys = Yii::$app->request->get('query');
        if (count($querys) > 0) {
            $typers = $querys['typer'];
            $user_id = $querys['users_id'];
            $b_time = $querys['b_time'];
            $e_time = $querys['e_time'];
            //$time = $querys['time'];
            if($typers>0) {
                $query = $query->andWhere(['admin_moneylog.typer'=>$typers]);
            }
            if($user_id) {
                $query = $query->andWhere(['like','usersname',$user_id]);
            }
            if($b_time) {
                $query = $query->andWhere(['>=','admin_moneylog.dates',$b_time]);
            }
            if($e_time) {
                $query = $query->andWhere(['<=','admin_moneylog.dates',$e_time]);
            }

        }
        //如果不是超级管理员，只能看到自己推荐的会员列表
        /*if($this->role_id != 1) {
            //自己的邀请码
            $vatation_code = $this->admin_user->vatation_code;
            $query = $query->andWhere(['admin_member.vatation_code2'=>$vatation_code]);
        }*/

        $pagination = new Pagination([
                'totalCount' => $query->count(),
                'pageSize' => '10',
                'pageParam' => 'page',
                'pageSizeParam' => 'per-page']
        );
        $products = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        return $this->render('index', [
            'model' => $products,
            'pages' => $pagination,
            'typer' => $typer,
            'query' => $querys,
        ]);
    }

    /**
     * Displays a single AdminMoneylog model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $typer[1] = '线上充值';
        $typer[2] = '线下充值';
        $typer[3] = '提现记录';
        $typer[4] = '提盈记录';
        $typer[5] = '追加记录';
        $model = $this->findModel($id);
        //如果不是超级管理员并且该会员不是此管理员的
        if( ($this->role_id != 1) && (AdminMember::findOne(['id'=>$model->users_id])->vatation_code2 != $this->admin_user->vatation_code)) {
            return $this->actionIndex();
        }
        $model->users_id = AdminMember::findOne(['id'=>$model->users_id])->usersname;
        return $this->render('view', [
            'model' => $model,
            'typer' => $typer,
        ]);

    }

    /**
     * Creates a new AdminMoneylog model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        //如果不是超级管理员
        if( $this->role_id != 1) {
            return $this->actionIndex();
        }
        $model = new AdminMoneylog();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing AdminMoneylog model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        //如果不是超级管理员
        if( $this->role_id != 1) {
            return $this->actionIndex();
        }
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing AdminMoneylog model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        //如果不是超级管理员
        if( $this->role_id != 1) {
            return $this->actionIndex();
        }
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionDelrecord(array $ids)
    {
        if (count($ids) > 0) {
            $c = AdminMoneylog::deleteAll(['in', 'id', $ids]);
            echo json_encode(array('errno' => 0, 'data' => $c, 'msg' => json_encode($ids)));
        } else {
            echo json_encode(array('errno' => 2, 'msg' => ''));
        }
    }

    /**
     * Finds the AdminMoneylog model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return AdminMoneylog the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = AdminMoneylog::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /*
     * 导出数据
     * */
    public function actionExport()
    {
        $arr_typer = [1=>'线上充值',2=>'线下充值',3=>'提现记录',4=>'提盈记录',5=>'追加记录'];
        $excel = new ExportExcelController();
        $model = AdminMoneylog::find()->joinWith('member')->asArray()->all();
        $data[] = ['序号','会员号','影响金额/$','可用金额/$','待收金额/$','交易类型','时间','ip','备注','操盘id'];
        foreach ($model as $k=> $arr) {
            $data[$k+1] = $arr;
            $data[$k+1]['dates'] = date('Y-m-d H:i:s',$arr['dates']);
            $data[$k+1]['users_id'] = $arr['member']['usersname'];
            $data[$k+1]['typer'] = $arr_typer[$arr['typer']];
            unset($data[$k+1]['member']);
        }
        $filename = '线上充值记录'.date('Ymd',time());
        $excel->download($data, $filename);
        //echo "<script>history.go(-1)</script>";

    }
}
