<?php



namespace backend\controllers;



use backend\models\AdminAccount;

use backend\models\AdminProduct;

use backend\models\AdminSetting;

use backend\models\AdminTongji;

use backend\models\AdminUser;

use backend\models\AdminUserRole;

use common\models\Common;

use Yii;

use backend\models\AdminMember;

use yii\data\ActiveDataProvider;

use yii\web\Controller;

use yii\web\NotFoundHttpException;

use yii\filters\VerbFilter;

use yii\data\Pagination;

use backend\models\AdminRegions;

use common\helps\Tools;

use backend\models\AdminHousekeeper;

use backend\models\AdminUserpeoduct;

use common\models\Excel;

use common\helps\ExportExcelController;

use common\models\UploadForm;

use yii\helpers\Url;



use yii\web\UrlManager;

/**

 * AdminMemberController implements the CRUD actions for AdminMember model.

 */

class AdminMemberController extends Controller

{

    /**

     * @inheritdoc

     */

    public $state = [0 => '未认证', 1 => '已认证'];

    public $layout = "lte_main";

    public $admin_id;

    public $role_id;

    public $admin_user;

    public $invitation;

    public $enableCsrfValidation = false ;

    public $level = 0;//分销等级

    public $code = [];



    public function behaviors()

    {

        return [

            'verbs' => [

                'class' => VerbFilter::className(),

                'actions' => [

                    'delete' => ['POST'],

                ],

            ],

        ];

    }



    public function init()

    {

        parent::init(); // TODO: Change the autogenerated stub

        $this->admin_id = yii::$app->session['__id'];

        //根据管理员id判断管理员的角色，超级管理员role_id为1

        $this->role_id = AdminUserRole::findOne(['user_id'=>yii::$app->session['__id']])->role_id;

        $this->admin_user = AdminUser::findOne(['id'=>yii::$app->session['__id']]);

        $this->invitation = Yii::$app->user->identity->vatation_code;

    }



    /**

     * Lists all AdminMember models.

     * @return mixed

     */

    public function actionIndex()
    {
        $account = AdminAccount::find()->all();
        //获取当前登录着的邀请码
        $query = AdminMember::find();
        $static = AdminMember::find();
        if($this->role_id==2){
           //下级代理的会员也要显示
            $admin_user = AdminUser::find()->where(['in','vatation_code2',$this->invitation])->all();
            if($admin_user){
                $this->getAgentMember($admin_user);
            }
            $this->code[] = $this->invitation;
            $query = AdminMember::find()->where(['in','vatation_code2',$this->code]);
            $static = AdminMember::find()->where(['in','vatation_code2',$this->code]);
        }
        $search = Yii::$app->request->get('query');
        // var_dump($search);
        $query = $this->condition($query,$search);
        $static = $this->condition($static,$search);
       // print_r($querys);
        $ky_money = [];
        $pagination = new Pagination([
                'totalCount' => $query->count(),
                'pageSize' => '10',
                'pageParam' => 'page',
                'pageSizeParam' => 'per-page']
        );
        $count_query = $query;
        //var_dump($count_data);exit;
        //select * from test order by case when num = -1 then 1 else 0 end desc;
        $sum = $static->select('sum(money) as money')->asArray()->one();
        $wrz = $static->select('id')->where(['state'=>0])->count();
        $rz = $static->select('id')->where(['state'=>1])->count();
        $products = $query->offset($pagination->offset)->orderBy("dates desc")
            ->limit($pagination->limit)
            ->all();
        $data['num'] = $count_query->count();
        //当天时间段



        $user=new AdminUser();

        $sonAgent=$user->getOptions3(Yii::$app->user->identity->id);

        $num = count($products);

        // var_dump($products);exit;

        return $this->render('index', [

            'data' => $data,

            'model' => $products,

            'pages' => $pagination,

            'query' => $search,

            'state' => $this->state,

            'role_id' => $this->role_id,

            'ky_money' => $ky_money,

            'account' => $account,

            'user'=>$sonAgent,

            'num' => $num,

            'sum' => $sum,

            'wrz' => $wrz,

            'rz' => $rz,

        ]);

    }





    public function actionRealname(){

        // echo 1111;exit;

        //     $realname = AdminMember::find()->where('state',3)->all();

        //     var_dump($realname);exit;

        //     return $this->render('realname',['realname'=>$realname]);

        $account = AdminAccount::find()->all();

        //获取当前登录着的邀请码

        $query = AdminMember::find();

        $static = AdminMember::find();

        if($this->role_id==2){

           //下级代理的会员也要显示

            $admin_user = AdminUser::find()->where(['in','vatation_code2',$this->invitation])->all();

            if($admin_user){

                $this->getAgentMember($admin_user);

            }

            $this->code[] = $this->invitation;

            $query = AdminMember::find()->where(['in','vatation_code2',$this->code]);

            $static = AdminMember::find()->where(['in','vatation_code2',$this->code]);

        }



        $search = Yii::$app->request->get('query');

        $query = $this->condition($query,$search);

        $static = $this->condition($static,$search);

       // print_r($querys);



        $ky_money = [];

        $pagination = new Pagination([

                'totalCount' => $query->count(),

                'pageSize' => '10',

                'pageParam' => 'page',

                'pageSizeParam' => 'per-page']

        );

        $count_query = $query;

        //var_dump($count_data);exit;

        //select * from test order by case when num = -1 then 1 else 0 end desc;

        $sum = $static->select('sum(balance) as balance')->asArray()->one();

        $wrz = $static->select('id')->where(['state'=>1])->count();

        $rz = $static->select('id')->where(['<>','state',1])->count();

        $products = $query->offset($pagination->offset)->where(array('state' => 3))

            ->orderBy("is_top desc,update_time desc,dates desc")

            ->limit($pagination->limit)

            ->all();

        $data['num'] = $count_query->count();

        //当天时间段

        $begin_today = strtotime(date('Y-m-d',time()));

        $end_today = $begin_today+24*60*60;

        $data['today_num'] = $count_query->andWhere(['between','dates',$begin_today,$end_today])->count();

        $user=new AdminUser();

        $sonAgent=$user->getOptions3(Yii::$app->user->identity->id);

        $num = count($products);

        return $this->render('index', [

            'data' => $data,

            'model' => $products,

            'pages' => $pagination,

            'query' => $search,

            'state' => $this->state,

            'role_id' => $this->role_id,

            'ky_money' => $ky_money,

            'account' => $account,

            'user'=>$sonAgent,

            'num' => $num,

            'sum' => $sum,

            'wrz' => $wrz,

            'rz' => $rz,

        ]);



    }



    /*

     * 返回代理下面代理的邀请码

     * 代理的代理。。。

     * $model

     * */

    protected function getAgentMember($model)

    {

        //获取其下面的代理

        //$admin_user = AdminUser::find()->where(['vatation_code2'=>$vatation_code])->all();

        $arr = [];

        foreach ($model as $key=> $list) {

            if($list->vatation_code) {

                //返回下面的代理的邀请码

                $this->code[] = $list->vatation_code;

                $arr[] = $list->vatation_code;

            }

        }

        $next_model = AdminUser::find()->where(['in','vatation_code2',$arr])->all();

        //如果存在下级代理

        if($next_model){

            $this->getAgentMember($next_model);

        }

        return $this->code;

    }



    /**

     * Displays a single AdminMember model.

     * @param string $id

     * @return mixed

     */

    public function actionView($id)

    {

        $model = $this->findModel($id);

        $model->bank_province = $model->bank_province?AdminRegions::findOne(['id'=>$model->bank_province])->name:'';

        $model->bank_city = $model->bank_city?AdminRegions::findOne(['id'=>$model->bank_city])->name:'';

        //$model->money = PublicController::getXgjInfo($model->xgj_name)->Balance;

        //$ky_money = PublicController::getXgjInfo($model->xgj_name)->Available;

        $card_pic = json_decode($model->cartfiles,true);

        $vatation_code = $model->vatation_code2;

        //下级代理的会员也要显示

        //$admin_user = AdminUser::find()->where(['in','vatation_code2',$this->invitation])->all();

        $admin_user = AdminUser::find()->where(['vatation_code2'=>$this->invitation])->all();

        if($admin_user){

            $this->getAgentMember($admin_user);

        }

        $this->code[] = $this->invitation;

        $all_member = AdminMember::find()->where(['in','vatation_code2',$this->code])->all();

        $all_member_id = [];

        if($all_member) {

            foreach ($all_member as $arr_member) {

                $all_member_id[] = $arr_member->id;

            }

        }

        //代理

        if( ($this->role_id == 2) && !in_array($id,$all_member_id)) {



            yii::$app->getSession()->setFlash('error', '没有该权限');

            echo "<script>window.history.go(-1)</script>";exit;

        }



        return $this->render('view', [

            'model' => $model,

            'state' => $this->state,

            'card_pic' => $card_pic,

            //'ky_money' => $ky_money,

            'role_id' => $this->role_id,

        ]);



    }



    /**

     * Creates a new AdminMember model.

     * If creation is successful, the browser will be redirected to the 'view' page.

     * @return mixed

     */

    public function actionCreate()

    {

        header('content-type:text/html;charset=utf8');

        //代理和风控没有添加权限

        if(in_array($this->role_id, [2,7])) {

            yii::$app->getSession()->setFlash('error', '没有该权限');

            echo "<script>window.history.go(-1)</script>";exit;

        }

        $model = new AdminMember();

        $code = Common::getCode();

        //print_r($code);

        if ($model->load((Yii::$app->request->post()))) {

            $id = $this->actionRandomgj();

            $onelist = AdminHousekeeper::find()->where(array('xgj_id' => $id))->one();

            $one = $onelist->attributes;

            //print_r($onelist);exit;

            $model->userspwd = Yii::$app->security->generatePasswordHash($model->userspwd);

            $model->xgj_name = $one['xgj_name'];

            $model->xgj_pwd = $one['xgj_pwd'];

            $model->vatation_code = $code;

            $cartfiles = explode(',',yii::$app->request->post('cartfiles'));

            $arr_file['zm'] = $cartfiles[0];

            $arr_file['fm'] = $cartfiles[1];

            //$arr_file['case'] = $cartfiles[2];

            $model->cartfiles = json_encode($arr_file);

            $model->bank_pic = yii::$app->request->post('bank_pic');

            if ($model->validate() == true && $model->save()) {

                AdminHousekeeper::updateAll(["states" => 1,'agentid'=>1], "xgj_id='$id'");

                return $this->redirect(['index']);

            } else {

                return $this->render('create', [

                    'model' => $model,

                    'code' => $code,

                    'state' => $this->state,

                ]);

            }

        } else {

            return $this->render('create', [

                'model' => $model,

                'code' => $code,

                'state' => $this->state,

            ]);



        }

    }



    //获取一名管家并修改其状态

    public function actionRandomgj($account='1')

    {

        //$one = AdminHousekeeper::find()->where(array('states' => 0))->one();

        //var_dump($account);exit;

        $one = AdminHousekeeper::find()->where(['states'=>0,'account_id'=>$account])->one();

        if ($one) {

            return $one->xgj_id;

        } else {

            echo "请添加信管家！";

            exit();

        }

    }





    /**

     * Updates an existing AdminMember model.

     * If update is successful, the browser will be redirected to the 'view' page.

     * @param string $id

     * @return mixed

     */

    public function actionUpdate($id)

    {

        // echo $id;exit;

        $account = AdminAccount::find()->all();

        $account_list = [];

        foreach ($account as $arr_list) {

            $account_list[$arr_list->id] = $arr_list->account;

        }

        $model = $this->findModel($id);

        $xgj_name1 = $this->findModel($id)->xgj_name;

       // $bank_province = $model->bank_province?AdminRegions::findOne(['id'=>$model->bank_province])->name:'';

        //$bank_city = $model->bank_city?AdminRegions::findOne(['id'=>$model->bank_city])->name:'';

        //$model->money = PublicController::getXgjInfo($model->xgj_name)->Balance;

        //$model->money = 0;

        //$ky_money = PublicController::getXgjInfo($model->xgj_name)->Available;

        //$ky_money = 0;

        $vatation_code = $model->vatation_code2;

        $card_pic = json_decode($model->cartfiles,true);

        //代理商

        if( $this->role_id == 2 ) {

            yii::$app->getSession()->setFlash('error', '没有该权限');

            echo "<script>window.history.go(-1)</script>";exit;

        }

        if ($model->load(Yii::$app->request->post())) {

            // var_dump(Yii::$app->request->post());exit;

             $pass =  Yii::$app->request->post("userspwd");

            if ($pass) {

                $model->userspwd = Yii::$app->security->generatePasswordHash($pass);

            }

            $xgj_name2 = Yii::$app->request->post("xgj_name");

            //如果信管家账号有修改

            if($xgj_name1 != $xgj_name2) {

                //判断信管家账号是否存在并且可用

                $is_xhj = AdminHousekeeper::find()->andwhere(['xgj_name'=>$xgj_name2])->andWhere(['states'=>0])->one();

                if(!$is_xhj) {

                    yii::$app->getSession()->setFlash('error', '信管家账号不存在或不可用');

                    //echo "<script>alert(1)</script>";exit;

                    echo "<script>window.history.go(-1)</script>";exit;

                }else {

                    $is_xhj->states = 1;

                    $is_xhj->save();

                }

            }

            $cartfiles = explode(',',yii::$app->request->post('cartfiles'));

            $arr_file['zm'] = $cartfiles[0];

            $arr_file['fm'] = $cartfiles[1];

            //$arr_file['case'] = $cartfiles[2];

            $model->cartfiles = json_encode($arr_file);

            $model->bank_pic = yii::$app->request->post('bank_pic');

            $model->xgj_name = yii::$app->request->post('xgj_name');

            $model->xgj_pwd = yii::$app->request->post('xgj_pwd');

            $model->money = yii::$app->request->post('money');

            if ($model->save(false)) {

                return $this->redirect(['index']);

            } else {

                return $this->render('update', [

                    'model' => $model,

                    'card_pic' => $card_pic,

                    //'ky_money' => $ky_money,

                    //'bank_province' => $bank_province,

                    //'bank_city' => $bank_city,

                    'account' => $account,

                    'account_list' => $account_list,

                    'role_id' => $this->role_id,

                    'state' => $this->state,

                ]);

            }

        } else {

            return $this->render('update', [

                'model' => $model,

                'card_pic' => $card_pic,

                //'ky_money' => $ky_money,

                //'bank_province' => $bank_province,

                //'bank_city' => $bank_city,

                'account' => $account,

                'account_list' => $account_list,

                'role_id' => $this->role_id,

                'state' => $this->state,

            ]);

        }

    }



    /**

     * Deletes an existing AdminMember model.

     * If deletion is successful, the browser will be redirected to the 'index' page.

     * @param string $id

     * @return mixed

     */

    public function actionDelete($id)

    {

        //代理

        if( ($this->role_id == 2) ) {

            return 800;

        }

        $this->findModel($id)->delete();



        return $this->redirect(['index']);

    }



    public function actionDelrecord(array $ids)

    {

        //代理

        if( ($this->role_id == 2) ) {

            return 800;

        }

        if (count($ids) > 0) {

            $c = AdminMember::deleteAll(['in', 'id', $ids]);

            echo json_encode(array('errno' => 0, 'data' => $c, 'msg' => json_encode($ids)));

        } else {

            echo json_encode(array('errno' => 2, 'msg' => ''));

        }

    }



    /**

     * Finds the AdminMember model based on its primary key value.

     * If the model is not found, a 404 HTTP exception will be thrown.

     * @param string $id

     * @return AdminMember the loaded model

     * @throws NotFoundHttpException if the model cannot be found

     */

    protected function findModel($id)

    {

        if (($model = AdminMember::findOne($id)) !== null) {

            return $model;

        } else {

            throw new NotFoundHttpException('The requested page does not exist.');

        }

    }



    //省市联动

    public function actionGetcity()

    {

        $provice_id = isset($_GET['provice_id']) ? $_GET['provice_id'] : 1;

        $provice = AdminRegions::find()->where(array('level' => 2, 'parent_id' => $provice_id))->all();

        $arr_provice = array();

        foreach ($provice as $val) {

            $arr_provice[$val->id] = $val->name;

        }

        //对获取到的地区数组转JSON格式

        header('Content-type: application/json');

        echo json_encode($arr_provice);

        exit();

    }



    //市区联动

    public function actionGetarea()

    {

        $city_id = isset($_GET['city_id']) ? $_GET['city_id'] : 2;

        $area = AdminRegions::find()->where(array('level' => 3, 'parent_id' => $city_id))->all();

        $arr_area = array();

        foreach ($area as $val) {

            $arr_area[$val->id] = $val->name;

        }

        //对获取到的地区数组转JSON格式

        header('Content-type: application/json');

        echo json_encode($arr_area);

        exit();

    }



    /*

     * 改变状态

     * */

    public function actionChange()

    {

        //代理

        if( ($this->role_id == 2) ) {

            return 800;

        }

        if(yii::$app->request->post()) {

            $state = yii::$app->request->post('state');

            $user_id = yii::$app->request->post('user_id');

            $account = yii::$app->request->post('account');

            $member = AdminMember::findOne(['id'=>$user_id]);

            $member->is_top=0;

            $member->update_time=time();

            if($member->state!=2) {

                //已审核

                return 400;

            }

            //根据会员找其代理商

            $agent = AdminUser::findOne(['vatation_code'=>$member->vatation_code2]);

            $member->state = $state;

            if($state==3) {

                $xgj_id = $this->actionRandomgj($account);

                $xgj = AdminHousekeeper::find()->where(array('xgj_id' => $xgj_id))->one();

                $member->xgj_name =$xgj->xgj_name;

                $member->xgj_pwd =$xgj->xgj_pwd;

                $member->account_id =$account;

                if($member->save()) {

                    AdminHousekeeper::updateAll(["states" => 1,'agentid'=>$agent->id], "xgj_id='$xgj_id'");

                    return 100;

                    //return json_encode($data,true);

                } else {

                    return 200;

                }

            }

            if($member->save()) {

                return 100;

                //return json_encode($data,true);

            } else {

                return 200;

            }





        }

    }



    /*

     * 获取用户信息

     * */

    public function actionGetInfo()

    {

        $id = Yii::$app->request->post('id');

        $onelist = AdminMember::find()->where(array('id' => "$id"))->asArray()->one();

        return json_encode($onelist);

    }



    /*

    * $url 链接地址

    * $size 二维码大小

    * $margin 外边距

    * 生成二维码

    * */

    public function actionQrcode($url='',$size=4, $margin=1)
    {
        $url = "http://www.xinniuniu.cn/index/register?vatation_code2".$this->admin_user->vatation_code;
        //引入二维码生成类
        require ROOT.'/phpqrcode/qrlib.php';
        //设置 header 头,直接输出图片
        Yii::$app->response->headers->set('Content-Type', 'image/png');
        //根据参数生成二维码 , 将其第二个参数值设为 false ,也就是不输出图片文件
        \QRcode::png($url, false, "L", $size, $margin);
        die();
    }



    public function actionDownloadImage()

    {

        $file = yii::$app->request->get('file');



        $wrstr=htmlspecialchars_decode(file_get_contents($file));

        $outfile=time().'.'.'jpg';

        header('Content-type: application/octet-stream; charset=utf8');

        Header("Accept-Ranges: bytes");

        header('Content-Disposition: attachment; filename='.$outfile);

        echo $wrstr;

        exit();

    }



    /*

     * 交易明细

     * */

    public function actionDetail($xgj_name)

    {

        //获取当前登录着的邀请码

        if($this->role_id==2){

            //$query = AdminTongji::find()->andWhere(['xgj_id'=>$xgj_name]);

        }

        $query = AdminTongji::find()->andWhere(['xgj_id'=>$xgj_name]);

        $querys = Yii::$app->request->get('query');

        if (count($querys) > 0) {

            //开始时间：05:59

            //结算时间：06:00

            $b_time = $querys['b_time'];

            $e_time = $querys['e_time'];

            if ($b_time) {

                $query = $query->andWhere(['>=', 'jy_time', $b_time]);

            }

            if ($e_time) {

                $query = $query->andWhere(['<=', 'jy_time', $e_time]);

            }

        }

            $pagination = new Pagination([

                    'totalCount' => $query->count(),

                    'pageSize' => '10',

                    'pageParam' => 'page',

                    'pageSizeParam' => 'per-page']

            );

            $detailes = $query->offset($pagination->offset)->orderBy("jy_time desc")

                ->limit($pagination->limit)

                ->all();

            return $this->render('detail', [

                'model' => $detailes,

                'pages' => $pagination,

                'query' => $querys,

                'role_id' => $this->role_id,

                'xgj_name' => $xgj_name,

            ]);



    }



    /*

     * 导入数据时，异步更新会员盈亏

     * 导入数据时，异步计算代理商的返佣金额

     * */

    public function actionUpdateProfit()

    {

        //每次导入数据的时候，将所有代理的提交返佣状态改成0

        AdminUserpeoduct::updateAll(['state'=>0]);

        $data = yii::$app->request->post('data');

        $aaaa = 0;

        foreach ($data as $key=> $list) {

            //计算会员的盈亏

            if($list) {

                $aaaa++;

                $file= "count.txt";

                file_put_contents($file, $aaaa);

                //计算会员的盈亏

                $this->dealMemberProfit($list);

                //计算所得的佣金

                $this->dealAgentCharge($list);

                //计算直系会员给代理产生的佣金

                $this->dealMemberCharge($list);

            }else{

                return 100;

            }

        }

        return 100;

    }



    /*

     * 处理代理的手续费

     * */

    protected function dealAgentCharge($list)

    {

        $member = AdminMember::find()->where(['xgj_name'=>$list['xgj_name']])->one();

        $model = AdminUser::find()->joinWith('info')->joinWith('daili')->andWhere(['vatation_code'=>$member->vatation_code2])->andWhere('admin_user_role.role_id <> 1')->one();

        //如果上级代理不是平台

        if($model) {

            //产品手续费,单位就是该产品的单位，如交易为欧元，返回的也是欧元

            $charge = $this->getAgentCharge($model,$list['contract']);

            $this->level = 0;

            $this->commission($model,$list,$charge,floatval($list['charge']));

        }

    }



    /*

     * 计算三级代理返佣,入库

     * $model $list

     * $charge 产品手续费

     * $profit 下级返佣的钱，一级代理是客户产生的，二级代理是在一级代理中设置的

     * */

    protected function commission($model,$list,$charge,$profit)

    {

        $file= "commission.txt";

        file_put_contents($file, $list['amount'].','.$this->level.','.$charge.','.$profit.PHP_EOL,FILE_APPEND);

        //该代理得到的佣金为

        $user_info = AdminUserpeoduct::findOne(['uid'=>$model->id]);

        //$money = floatval($profit)-$charge;

        if($this->level==0) {

            $money = floatval($profit)-$charge*(intval($list['amount']));

        }else{

            /*可能出现问题*/

            //$money = (floatval($profit)-$charge)*2;

            $money = (floatval($profit)-$charge)*intval($list['amount']);

        }

        //汇率

        $rate = json_decode($model->info['rate'],true);

        $user_info->commission_amount += ($this->formatAgentMoney($list['currency'],$money,$rate));

        //截佣，如果上级代理不是一级代理

        $pre_model = AdminUser::find()->joinWith('info')->joinWith('daili')->andWhere(['vatation_code'=>$model->vatation_code2])->andWhere('admin_user_role.role_id <> 1')->one();

        if($pre_model) {

            $charge1 = $this->getAgentCharge($pre_model,$list['contract']);

            $the_charge = (floatval($charge)-floatval($charge1))*intval($list['amount']);

            $user_info->commission_agent += ($this->formatAgentMoney($list['currency'],$the_charge,$rate));

        }



        file_put_contents("money.txt", $this->formatAgentMoney($list['currency'],$money,$rate).','.$profit.PHP_EOL,FILE_APPEND);

        if($user_info->save()){

            $this->level++;

            //查询上一级代理

            $pre_model = AdminUser::find()->joinWith('info')->joinWith('daili')->andWhere(['vatation_code'=>$model->vatation_code2])->andWhere('admin_user_role.role_id <> 1')->one();

            //上级代理不是平台，并且是三级代理以内

            if($pre_model && $this->level<3) {

                $pre_charge = $this->getAgentCharge($pre_model,$list['contract']);

                $this->commission($pre_model,$list,$pre_charge,$charge);

            }

        }



    }



    /*

     * 根据返回改代理设置的产品手续费，将结果除以2返回

     * 产品代码 $contract

     * */

    protected function getAgentCharge($model,$contract)

    {

        $arr_proid = explode(',',$model->info['proid']);

        $arr_price = explode(',',$model->info['price']);

        $arr = [];

        foreach ($arr_proid as $k=> $val) {

            $arr[$val] = $arr_price[$k];

        }

        //$arr  获得的是以产品id为下表，价格为值的一维数组

        //根据合约号获取产品id

        $pro_id = AdminProduct::findOne(['code'=>$contract])->id;

        //设置的代理费用

        $charge = floatval($arr[$pro_id]);

        return (intval($charge*100))/200;

    }



    /*

     * 格式化代理的手续费返佣，单位为人民币

     * $currency 货币

     * $money 金额

     * $rate 汇率

     * */

    protected function formatAgentMoney($currency,$money,$rate)

    {

        if($currency=='USD') {

            //$rate = 1;

        } else if($currency=='EUR') {

            $money = $money*$rate['eur_usd'];

        } else if($currency=='HKD') {

            $money = $money/$rate['usd_hkd'];

        }

        $rate_usd = $rate['usd_rmb'];

        return (intval($money*$rate_usd*100))/100;

    }



    /*

     * 处理会员盈亏，美元统计

     * */

    protected function dealMemberProfit($list)

    {

        $member = AdminMember::findOne(['xgj_name'=>$list['xgj_name']]);

        if($list['currency']=='USD') {

            $money = floatval($list['pc_yingkui']);

        } else if($list['currency']=='EUR') {

            $money = floatval($list['pc_yingkui']*Tools::getSetting(23));

        } else if($list['currency']=='HKD') {

            $money = floatval($list['pc_yingkui']/Tools::getSetting(25));

        }

        $member->profit_money += number_format($money,4);

        $member->save();

    }



    /*

     * 处理直系会员给代理产生的佣金

     * */

    protected function dealMemberCharge($list)

    {

        $member = AdminMember::findOne(['xgj_name'=>$list['xgj_name']]);

        //查找上级不是管理员的代理

        //$model_user = AdminUser::findOne(['vatation_code'=>$member->vatation_code2]);

        $model = AdminUser::find()->joinWith('info')->joinWith('daili')->andWhere(['vatation_code'=>$member->vatation_code2])->andWhere('admin_user_role.role_id <> 1')->one();

        if($model) {

            $model_info = AdminUserpeoduct::findOne(['uid'=>$model->id]);

            //汇率

            $rate = json_decode($model_info->rate,true);

            //返给上级代理的佣金

            $charge = $this->getAgentCharge($model,$list['contract']);

            $money = floatval($list['charge'])-$charge*(intval($list['amount']));

            $model_info->commission_member += ($this->formatAgentMoney($list['currency'],$money,$rate));

            $model_info->save();

        }

    }



    /**

     * 弹窗

     */

    public function actionOpen()

    {

        $account = AdminAccount::find()->all();

        return $this->renderPartial('open',[

            'account'=>$account

        ]);

    }



    /**

     * 生成excel

     * $field 表头数据

     * $data 数据

     */

    public function actionExport()

    {

        if( !in_array($this->role_id, [1,6]) ) {

            yii::$app->getSession()->setFlash('error', '没有该权限');

            echo "<script>window.history.go(-1)</script>";exit;

        }

        $arr_state = [0=>'未审核',1=>'通过',2=>'未通过'];

        $excel = new ExportExcelController();

        $search = Yii::$app->request->get('query');

        $model = $this->condition(AdminMember::find(),$search)->asArray()->all();

        //$model = AdminCharge::find()->joinWith('member')->asArray()->all();

        $data[] = ['姓名','手机号','余额','实名状态','邀请码','注册日期'];

        foreach ($model as $k=> $arr) {



            $data[$k+1]['realname'] = $arr['realname']?:'未认证';

            $data[$k+1]['tel'] = $arr['tel'];

            $data[$k+1]['balance'] = $arr['balance'];

            $data[$k+1]['state'] = $this->state[$arr['state']];

            $data[$k+1]['vatation_code2'] = $arr['vatation_code2'];

            $data[$k+1]['dates'] = date('Y-m-d H:i:s',$arr['dates']);

        }

        $filename = '用户列表'.date('Ymd',time());

        $excel->download($data, $filename);

        //echo "<script>history.go(-1)</script>";



    }

    public function actionExport2()

    {

        $search = Yii::$app->request->get('query');

        $modelLabel = new AdminMember();

        $field  = [];

        $data = [];

        $key_arr = ['realname','tel','balance','state'];

        foreach ($key_arr as $k1=> $v) {

            $field[$k1]['key'] = $v;

            $field[$k1]['name'] = $modelLabel->getAttributeLabel($v);

        }

        $model = $this->condition(AdminMember::find(),$search)->all();



        foreach ($model as $k=> $list) {

            $data[$k]['realname'] = $list->realname;

            $data[$k]['tel'] = $list->tel;

            $data[$k]['balance'] = $list->balance;

            $data[$k]['state'] = $list->state;



//            foreach ($list as $key=> $val) {

//                if(in_array($key,$key_arr)) {

//                    $data[$k][$key] = $this->format($key,$val);

//                }

//            }

        }

        //print_r($data);exit;

        Excel::createExcelFromData($field, $data, date('Ymd').'data.csv');

    }



    /**

     * 格式化数据，导出excel时，有些数据需要格外处理

     * @param $key

     * @param $val

     * @return mixed|string

     */

    protected function format($key,$val)

    {

        if(in_array($key,['province','city','area','type','status'])) {

            if($key=='type') {

                return $this->type[$val];

            }else if($key=='status') {

                return $this->status[$val];

            }else {

                if($val) {

                    return AdminRegions::getRegionName($val);

                }else {

                    return '无';

                }

            }

        }else {

            return $val?:'无';

        }

    }

    /**

     * 搜索条件

     * @param $query

     * @param $search

     * @return mixed

     */

    protected function condition($query,$search)

    {

        if (count($search) > 0) {

            $realname = $search['realname'];

            $tel = $search['tel'];

            if ($realname) {

                $query = $query->andWhere(['like', 'realname', $realname]);

            }

            if ($tel) {

                $query = $query->andWhere(['like', 'tel', $tel]);

            }

            if ($search['b_time']) {

                $b_time = strtotime($search['b_time']);

                $query = $query->andWhere(['>=', 'admin_member.dates', $b_time]);

            }

            if ($search['e_time']) {

                $e_time = strtotime($search['e_time']);

                $query = $query->andWhere(['<=', 'admin_member.dates', $e_time]);

            }

            if (intval($search['state']) >= 0) {

                $query = $query->andWhere(['state' => $search['state']]);

            }

        }

        return $query;

    }



    /**

     * 会员转挂

     * @return \yii\web\Response

     */

    public function actionHanging()
    {
        if(Yii::$app->request->isPost){
            $uid=Yii::$app->request->post('uid');
            $pid=Yii::$app->request->post('pre_id');
            $member=AdminMember::findOne($uid);
            $parent=AdminUser::findOne($pid);
            $member->pid=$pid;
            $member->vatation_code2=$parent->vatation_code;
            if($member->save(false)){
                return $this->redirect(['index']);
            }
        }
    }
    /**
     * 解绑实名
     */
    public function actionSmRz()
    {
        $id = Yii::$app->request->post('id');
        $member = AdminMember::findOne($id);
        $member->state = '0';
        if($member->save(false)){
            return 600;
        }
    }

    /**
     * 改变余额
     */
    public function actionMoney()
    {
        $id = (int)Yii::$app->request->post('id');
        $money = Yii::$app->request->post('money');
        if(!is_numeric($money)){
            return json_encode(['status'=>100,'msg'=>'金额输入有误']);
        }
        $member = AdminMember::findOne($id);
        $member->money = $money;
        if($member->save()){
            return json_encode(['status'=>200,'msg'=>'修改成功']);
        }else{
            return json_encode(['status'=>100,'msg'=>'修改失败']);
        }
    }

}

